# RealSense D435i Camera Configuration
# Calibrated for specific device

camera:
  ros__parameters:
    # Device settings
    serial_no: ""  # Leave empty for first available camera
    enable_color: true
    enable_depth: false
    enable_infra: false
    
    # Color camera settings (from calibration)
    color_width: 1920
    color_height: 1080
    color_fps: 30
    
    # Calibration data (from Intel RealSense calibration)
    color_intrinsics:
      fx: 961.267
      fy: 961.267
      ppx: 964.3
      ppy: 538.868
      model: 'plumb_bob'
    
    # Image quality settings
    enable_auto_exposure: true
    enable_auto_white_balance: true
    color_backlight_compensation: false
    color_brightness: 0
    color_contrast: 50
    color_gain: 64
    color_gamma: 300
    color_hue: 0
    color_saturation: 64
    color_sharpness: 50
    color_white_balance: 4600
    
    # Stream settings
    publish_tf: false
    tf_publish_rate: 0.0
    clip_distance: 3.0
    linear_accel_cov: 0.01
    angular_velocity_cov: 0.01
    
    # USB settings
    usb_port_id: ""  # Leave empty to auto-detect
    reconnect_timeout: 6.0
    
    # World transform (from calibration)
    world_transform:
      rotation:
        x: [0.99995, -0.000619295, 0.00998492]
        y: [0.000614008, 1.0, 0.000532623]
        z: [-0.00998525, -0.000526465, 0.99995]